#!/usr/bin/perl -w
#
#    The main script of the rsu-client, this takes care of overhead stuff
#    Copyright (C) 2011-2013  HikariKnight
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
####
# All files(except jagexappletviewer.jar) and modules used by this script
# uses the same license stated above unless something else is specified
# in their header. External commands use their own license
####
# Be strict to avoid messy code
use strict;

# Use FindBin module to get script directory
use FindBin;

# Get script directory
my $cwd = $FindBin::RealBin;
# Get script filename
my $scriptname = $FindBin::Script;
# Detect the current OS
my $OS = "$^O";

# URL for the maclibs download
my $maclib_url = "https://dl.dropbox.com/u/11631899/opensource/Perl/runescape_unix_client/modules/darwin.tar.gz";

# run the script
main();

sub main
{
	# Get the architecture
	my $arch = `uname -m`;
	
	# If we are on 64bit
	if ($arch =~ /(x86_64|amd64)/)
	{
		# Use x86_64 as architecture
		$arch = "-x86_64";
	}
	# Else if we are on 32bit
	elsif($arch =~ /i\d{1,1}86/)
	{
		# Use i386 as architecture
		$arch = "-i386";
	}
	# Else we are on an architecture that does not support the launcher
	else
	{
		# Install the menu icons and launch runescape
		system "$cwd/install-desktop-icons & $cwd/runescape @ARGV";
		
		# Exit once we are done so we dont trigger the launcher
		exit;
	}
	
	# If we are on Linux
	if($OS =~ /linux/)
	{
		# Launch the launcher for the correct architecture
		system "$cwd/modules/linux/rsu-launcher/rsu-launcher$arch @ARGV &";
	}
	# Else if we are on darwin/osx
	elsif($OS =~ /darwin/)
	{
		# Run a check to see if the mac libraries are installed
		checkformaclibs();
		
		# Launch the launcher for mac osx
		system "$cwd/modules/$OS/rsu-launcher/rsu-launcher-$OS @ARGV &";
	}
	# Else
	else
	{
		# Launch the launcher for the correct OS
		system "$cwd/modules/$OS/rsu-launcher/rsu-launcher$arch @ARGV &";
	}
}

#
#---------------------------------------- *** ----------------------------------------
#

sub fetchmaclibs
{
	# Download the perl bundle containing the libraries and extract the archive inside the modules folder
	system "cd \"$cwd/modules\" && curl -o \"$cwd/modules/darwin.tar.gz\" $maclib_url && tar -zxvf \"$cwd/modules/darwin.tar.gz\" && rm \"$cwd/modules/darwin.tar.gz\"";
}

#
#---------------------------------------- *** ----------------------------------------
#

sub checkformaclibs
{
	# Make a variable to contain the directory list
	my $maclibs;
	
	if ($OS =~ /darwin/)
	{
		# Get a list of files in the client directory
		$maclibs = `ls "$cwd/modules"`;
	}
	
	# If we are running on darwin/MacOSX and the darwin folder does not exist
	if ($OS =~ /darwin/ && $maclibs !~ /darwin/)
	{
		# Display a message prompting the user to download an archive file containing the rsu-settings_mac loader(self contained minimal wxperl) and the wxWidgets libraries.
		print "The rsu-launcher requires extra libraries on MacOSX
(because apple broke their own in 10.5 and up)
So i have packaged a custom loader with a working version of wxWidgets
for use by this script to save you 1 - 2 hours of your life
compiling it yourself.

NOTE: If you want the sourcecode for the loader,
go to $cwd/modules/$OS/rsu-launcher/rsu-launcher-$OS
and add .zip behind the \"rsu-launcher-$OS\" and extract the archive.

Is it ok for me to download these libraries into the client directory?
Answer with yes or no (default = yes):";

		# Wait for users answer
		my $answer = <STDIN>;
		
		# If the user answers no
		if ($answer =~ /(no|n)/i)
		{
			# Exit the script
			exit;
		}
		else
		{
			fetchmaclibs();
		}
	}
}

#
#---------------------------------------- *** ----------------------------------------
#

